Added Maestrocloud tests

diff --git a/.github/workflows/maestro.yaml b/.github/workflows/maestro.yaml
--- a/.github/workflows/maestro.yaml
+++ b/.github/workflows/maestro.yaml
@@ -30,24 +30,25 @@ jobs:
           echo 'export PATH="$PATH:$HOME/.maestro/bin"' >> $GITHUB_ENV
           
           # Verify Maestro installation
-          maestro --version || echo "Maestro installation failed"
+          ~/.maestro/bin/maestro --version || echo "Maestro installation failed"
 
       - name: Install Maestro CLI Globally
         run: |
-          curl -Ls "https://get.maestro.mobile.dev" | bash
+          # Move Maestro CLI to a globally accessible path
           sudo mv $HOME/.maestro/bin/maestro /usr/local/bin/
-    
-          # Verify Installation
-          maestro --version      
+          
+          # Verify Global Installation
+          maestro --version || echo "Global Maestro installation failed"
 
       - name: Debug Maestro Installation
         run: |
+          # Print PATH and check locations
           echo "PATH: $PATH"
           ls -la $HOME/.maestro/bin/
           which maestro
 
       - name: Run Maestro tests on Maestro Cloud
-        run: npm run test:calculation:cloud
+        run: ~/.maestro/bin/maestro cloud -e APP_ID=com.google.android.calculator --apiKey=${{ secrets.MAESTRO_CLOUD_API_KEY }} --app-file=app/Calculator.apk android
         env:
           MAESTRO_CLOUD_API_KEY: 164a4ca2-3f65-44ab-bf1c-2bde9a858fac
-          MAESTRO_PROJECT_ID: ${ APP_ID }
+          MAESTRO_PROJECT_ID: ${APP_ID }
